"""initial schema

Revision ID: 3fb051bfd85e
Revises: 
Create Date: 2026-10-06 17:49:49.153469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb051bfd85e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gstins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('registration_type', sa.Enum('regular', 'composition', 'sez_unit', 'isd', 'casual', name='registrationtype', native_enum=False, length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('advance_tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('advance_tax_from', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_table('advance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('advance_voucher_no', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advance_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advance_rules_gstin_id'), ['gstin_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('kind', sa.Enum('sales_register', 'purchase_register', 'gstr2a', 'gstr2b', 'advance_register', 'advance_opening', name='importkind', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('tally', 'excel', 'gst_portal', name='importsource', native_enum=False, length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index('ix_import_batches_gstin_period_kind', ['gstin_id', 'period', 'kind'], unique=False)

    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sac', sa.String(length=8), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('land_deduction', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin_id', 'name', name='uq_service_type_name')
    )
    op.create_table('tax_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('entry_type', sa.Enum('liability', 'itc', 'itc_reversal', 'utilisation', 'cash_payment', name='ledgerentrytype', native_enum=False, length=32), nullable=False),
    sa.Column('tax_head', sa.Enum('IGST', 'CGST', 'SGST', 'CESS', name='taxhead', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('offset_head', sa.Enum('IGST', 'CGST', 'SGST', 'CESS', name='taxhead', native_enum=False, length=32), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_tax_ledger_gstin_period', ['gstin_id', 'period'], unique=False)

    op.create_table('advance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('entry_type', sa.Enum('advance', 'opening', 'refund', name='advanceentrytype', native_enum=False, length=32), nullable=False),
    sa.Column('voucher_no', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_gstin', sa.String(length=15), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('against_voucher_no', sa.String(length=50), nullable=True),
    sa.Column('narration', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advance_entries', schema=None) as batch_op:
        batch_op.create_index('ix_advance_entries_gstin_period', ['gstin_id', 'period'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('direction', sa.Enum('outward', 'inward', name='direction', native_enum=False, length=32), nullable=False),
    sa.Column('doc_type', sa.Enum('INV', 'CRN', 'DBN', name='doctype', native_enum=False, length=32), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('counterparty_gstin', sa.String(length=15), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.Column('reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('supply_category', sa.Enum('taxable', 'export_wpay', 'export_wopay', 'sez_wpay', 'sez_wopay', 'deemed_export', 'nil_rated', 'exempt', 'non_gst', name='supplycategory', native_enum=False, length=32), nullable=False),
    sa.Column('itc_eligible', sa.Boolean(), nullable=True),
    sa.Column('invoice_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('source_rows', sa.JSON(), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_counterparty_gstin'), ['counterparty_gstin'], unique=False)
        batch_op.create_index('ix_invoices_gstin_period_dir', ['gstin_id', 'period', 'direction'], unique=False)
        batch_op.create_index('ix_invoices_lookup', ['gstin_id', 'direction', 'invoice_no'], unique=False)

    op.create_table('portal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('source', sa.Enum('sales_register', 'purchase_register', 'gstr2a', 'gstr2b', 'advance_register', 'advance_opening', name='importkind', native_enum=False, length=32), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('doc_type', sa.Enum('INV', 'CRN', 'DBN', name='doctype', native_enum=False, length=32), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.Column('reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('invoice_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('itc_available', sa.Boolean(), nullable=True),
    sa.Column('itc_unavailable_reason', sa.String(length=255), nullable=True),
    sa.Column('supplier_return_filed', sa.Boolean(), nullable=True),
    sa.Column('supplier_filing_date', sa.Date(), nullable=True),
    sa.Column('supplier_filing_period', sa.String(length=7), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_documents', schema=None) as batch_op:
        batch_op.create_index('ix_portal_docs_gstin_period', ['gstin_id', 'period', 'source'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_documents_supplier_gstin'), ['supplier_gstin'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('hsn', sa.String(length=8), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uqc', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('land_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('portal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_documents_supplier_gstin'))
        batch_op.drop_index('ix_portal_docs_gstin_period')

    op.drop_table('portal_documents')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_lookup')
        batch_op.drop_index('ix_invoices_gstin_period_dir')
        batch_op.drop_index(batch_op.f('ix_invoices_counterparty_gstin'))

    op.drop_table('invoices')
    with op.batch_alter_table('advance_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_advance_entries_gstin_period')

    op.drop_table('advance_entries')
    with op.batch_alter_table('tax_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_tax_ledger_gstin_period')

    op.drop_table('tax_ledger_entries')
    op.drop_table('service_types')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batches_gstin_period_kind')
        batch_op.drop_index(batch_op.f('ix_import_batches_file_sha256'))

    op.drop_table('import_batches')
    with op.batch_alter_table('advance_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advance_rules_gstin_id'))

    op.drop_table('advance_rules')
    op.drop_table('gstins')
    op.drop_table('entities')
    # ### end Alembic commands ###
