"""cost centres

Revision ID: 474f33ddd08c
Revises: 3fb051bfd85e
Create Date: 2026-10-06 21:11:25.466245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474f33ddd08c'
down_revision: Union[str, Sequence[str], None] = '3fb051bfd85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin_id', 'name', name='uq_cost_centre_name')
    )
    with op.batch_alter_table('advance_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_centre_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_advance_entries_cost_centre_id'), ['cost_centre_id'], unique=False)
        batch_op.create_foreign_key('fk_advance_entries_cost_centre', 'cost_centres', ['cost_centre_id'], ['id'])

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_centre_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoice_items_cost_centre_id'), ['cost_centre_id'], unique=False)
        batch_op.create_foreign_key('fk_invoice_items_cost_centre', 'cost_centres', ['cost_centre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_items_cost_centre', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoice_items_cost_centre_id'))
        batch_op.drop_column('cost_centre_id')

    with op.batch_alter_table('advance_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_advance_entries_cost_centre', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_advance_entries_cost_centre_id'))
        batch_op.drop_column('cost_centre_id')

    op.drop_table('cost_centres')
    # ### end Alembic commands ###
